import pytest
from day11.script import Solver

starting_universe = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""

expanded_universe = """....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#......."""

def test_Solver_parse_input():
    solver = Solver(starting_universe.split('\n'))
    solver.parse_input()
    assert solver.grid.height == 10
    assert solver.grid.width == 10
    solver.double_space()
    assert solver.grid.height == 12
    assert solver.grid.width == 13

# @pytest.mark.parametrize('from_galaxy,to_galaxy,expected', [
#     ((),(),9)
# ])
# def test_Solver_find_length(input : str, expected : int):
#     solver = Solver(input.split('\n'))
#     solver.parse_input()
#     actual = solver.find_length()
#     assert actual == expected